package models.question;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import models.data.Language;

/**
 * 
 * @author Ruben Taelman
 *
 */
public abstract class Question {
	protected QuestionType type;
	private List<Language> languages;
	private String ID;
	private Map<Language, String> titles;
	private boolean official;
	private boolean active;
	private Server server;
	
	/**
	 * Don't just call this, Question need to be generated by calling the static getFromXml(String xml)
	 */
	protected Question() {
		this.languages = new ArrayList<Language>();
		this.titles = new HashMap<Language, String>();
	}
	
	public static Question getFromXml(String xml) {
		// This is only a stub implementation !
		Question q = new MultipleChoiceQuestion();
		Language langEn = new Language("en", "language.en");
		q.titles.put(langEn, "This is a cool question");
		q.languages.add(langEn);
		q.ID="TEST01234";
		return q;
	}
	
	public boolean isOfficial() {
		return official;
	}
	
	public void setOfficial(boolean official) {
		this.official = official;
	}
	
	public boolean isActive() {
		return active;
	}
	
	public void setActive(boolean active) {
		this.active = active;
	}
	
	public Server getServer() {
		return server;
	}
	
	public void setServer(Server server) {
		this.server = server;
	}
	
	public QuestionType getType() {
		return type;
	}
	
	public List<Language> getLanguages() {
		return languages;
	}
	
	public String getID() {
		return ID;
	}
	
	public Map<Language, String> getTitles() {
		return titles;
	}
}
